/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\NavigationTest.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function NavigationTest(props) {

  const ref = useRef()

  const navigateTo = (place) => {
    alert(place)
  }


  const { nodes, materials } = useGLTF('../../public/NavigationTest.glb')
  return (
    <group {...props} dispose={null}>
      <mesh ref={ref} onClick={() => navigateTo("Bleu")} geometry={nodes.Cube.geometry} material={materials.Bleu} />
      <mesh onClick={() => navigateTo("Vert")} geometry={nodes.Cube001.geometry} material={materials.Green} position={[-4.668, 0, -5.338]} />
      <mesh onClick={() => navigateTo("Marron")} geometry={nodes.Cube002.geometry} material={materials.Broon} position={[1.202, 0, -8.027]} />
      <mesh onClick={() => navigateTo("Rouge")} geometry={nodes.Red.geometry} material={materials.Red} position={[0, 0, 4.307]} />
    </group>
  )
}

useGLTF.preload('../../public/NavigationTest.glb')
