/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\OtherWorld.glb
*/
import { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'

export function OtherWorld(props) {
  const earth = useRef()



  const { nodes, materials } = useGLTF('./../../OtherWorld.glb')
  // eslint-disable react/no-unknown-property
  return (
    <group {...props} dispose={null}>
      <directionalLight intensity={1} decay={2} position={[57.853, 61.73, 65.069]} rotation={[-Math.PI / 2, 0, -1.448]} scale={15.468} />
      <directionalLight intensity={1} decay={2} position={[-65.924, 61.73, 70.425]} rotation={[-Math.PI / 2, 0, -1.448]} scale={15.468} />
      <directionalLight intensity={1} decay={2} position={[-57.853, 58.621, -0.965]} rotation={[-Math.PI / 2, 0, -1.448]} scale={15.468} />
      <directionalLight intensity={1} decay={2} position={[65.55, 61.73, -16.68]} rotation={[-Math.PI / 2, 0, -1.448]} scale={15.468} />

      <Float speed={0.8} floatIntensity={0.01}>
        {/* Volcano */}
        <group position={[-100, 40, -9.807]} rotation={[0, -1.448, -0.2]} scale={25}>
          <mesh geometry={nodes.mesh125708411.geometry} material={materials.mat20} />
          <mesh geometry={nodes.mesh125708411_1.geometry} material={materials.mat9} />
          <mesh geometry={nodes.mesh125708411_2.geometry} material={materials.None} />
        </group>
      </Float>

      <Float speed={0.4} floatIntensity={0.01}>
        {/* wind */}
        <group position={[-90.239, 10.767, 66.344]} rotation={[0, -1.448, 0]} scale={14.584}>
          <mesh geometry={nodes['forest-Mesh'].geometry} material={materials['None.001']} />
          <mesh geometry={nodes['forest-Mesh_1'].geometry} material={materials['mat20.001']} />
          <mesh geometry={nodes['forest-Mesh_2'].geometry} material={materials['mat9.001']} />
          <mesh geometry={nodes['forest-Mesh_3'].geometry} material={materials.lambert4SG} />
          <mesh geometry={nodes['forest-Mesh_4'].geometry} material={materials.lambert2SG} />
          <mesh geometry={nodes['forest-Mesh_5'].geometry} material={materials['lambert3SG.001']} />
        </group>
      </Float>

      <Float speed={0.7} floatIntensity={0.01}>
        {/* Water */}
        <group position={[90.239, -10.767, 66.344]} rotation={[0, -1.5, -0.1]} scale={15.468}>
          <mesh geometry={nodes.mesh125708411002.geometry} material={materials['mat20.002']} />
          <mesh geometry={nodes.mesh125708411002_1.geometry} material={materials['mat9.002']} />
          <mesh geometry={nodes.mesh125708411002_2.geometry} material={materials.Waterfall_mat1} />
        </group>
      </Float>

      <Float speed={0.5} floatIntensity={0.01}>
        {/* earth */}
        <group ref={earth} position={[100, 35, -9.807]} rotation={[0, -1.448, -0.2]} scale={25}>
          <mesh geometry={nodes.mesh125708411003.geometry} material={materials['mat20.003']} />
          <mesh geometry={nodes.mesh125708411003_1.geometry} material={materials['mat9.003']} />
          <mesh geometry={nodes.mesh125708411003_2.geometry} material={materials.Landscape} />
        </group>
      </Float>

      {/*<Float>*/}
        {/* computer */}
        {/*<group onClick={() => alert("computer")} position={[-2.953, -0.382, -126.582]} rotation={[0, -1.448, 0]} scale={100}>*/}
        {/*  <mesh geometry={nodes.mesh1810082506004.geometry} material={materials['mat9.004']} />*/}
        {/*  <mesh geometry={nodes.mesh1810082506004_1.geometry} material={materials['mat20.004']} />*/}
        {/*  <mesh geometry={nodes.mesh1810082506004_2.geometry} material={materials.mat16} />*/}
        {/*  <mesh geometry={nodes.mesh1810082506004_3.geometry} material={materials.mat23} />*/}
        {/*  <mesh geometry={nodes.mesh1810082506004_4.geometry} material={materials.mat17} />*/}
        {/*  <mesh geometry={nodes.mesh1810082506004_5.geometry} material={materials.mat25} />*/}
        {/*  <mesh geometry={nodes.mesh1810082506004_6.geometry} material={materials.mat15} />*/}
        {/*</group>*/}
      {/*</Float>*/}
    </group>
  )
}

useGLTF.preload('./../../OtherWorld.glb')
