/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\tiny7.glb 
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import gsap from 'gsap';
import { useFrame } from '@react-three/fiber';

export const FLOOR_HEIGHT = 2
export const NB_FLOORS = 2

export function Tiny7(props) {
  const { nodes, materials } = useGLTF('../../public/tiny7.glb')
  const ref = useRef();
  const tl = useRef()

  const scroll = useScroll();

  useFrame(() => {
    tl.current.seek(scroll.offset * tl.current.duration());
  })

  useLayoutEffect(() => {
    tl.current = gsap.timeline();

    tl.current.to(
      ref.current.rotation, {
      duration: 2,
      // z: -FLOOR_HEIGHT * (NB_FLOORS - 1),
      // x: -FLOOR_HEIGHT * (NB_FLOORS - 1),
      y: FLOOR_HEIGHT * (NB_FLOORS - 1),
    },
      ref.current.position,
      {
        duration: 2,
        z: -FLOOR_HEIGHT * (NB_FLOORS - 1),
        x: -FLOOR_HEIGHT * (NB_FLOORS - 1),
        y: -FLOOR_HEIGHT * (NB_FLOORS - 1),
      }
    )
  })

  const animateForm = () => {
      ref.current.rotation, {
      duration: 20000,
      // z: -FLOOR_HEIGHT * (NB_FLOORS - 1),
      // x: -FLOOR_HEIGHT * (NB_FLOORS - 1),
      y: 1000,
    }
  }

  return (
    <group {...props} dispose={null} ref={ref} onClick={() => animateForm}>
      <mesh geometry={nodes.Sphere046.geometry} material={materials['Material.006']} position={[7.029, -0.79, 1.96]} scale={-0.313} />
      <mesh geometry={nodes.Sphere045.geometry} material={materials['Material.006']} position={[7.239, -0.683, 2.22]} scale={-0.313} />
      <mesh geometry={nodes.Sphere044.geometry} material={materials['Material.006']} position={[7.856, -0.769, 2.66]} scale={-0.313} />
      <mesh geometry={nodes.Sphere043.geometry} material={materials['Material.006']} position={[7.539, -0.705, 2.451]} scale={-0.313} />
      <mesh geometry={nodes.Sphere042.geometry} material={materials['Material.006']} position={[7.543, -0.772, -2.501]} scale={-0.313} />
      <mesh geometry={nodes.Sphere041.geometry} material={materials['Material.006']} position={[7.295, -0.733, -2.21]} scale={-0.313} />
      <mesh geometry={nodes.Sphere040.geometry} material={materials['Material.006']} position={[7.221, -0.777, -2.18]} scale={-0.313} />
      <mesh geometry={nodes.Sphere039.geometry} material={materials['Material.006']} position={[7.771, -0.761, -1.713]} scale={-0.313} />
      <mesh geometry={nodes.Sphere038.geometry} material={materials['Material.006']} position={[7.537, -0.761, -1.906]} scale={-0.313} />
      <mesh geometry={nodes.Sphere037.geometry} material={materials['Material.006']} position={[6.255, -0.746, -4.787]} scale={-0.313} />
      <mesh geometry={nodes.Sphere036.geometry} material={materials['Material.006']} position={[6.045, -0.771, -4.98]} scale={-0.313} />
      <mesh geometry={nodes.Sphere035.geometry} material={materials['Material.006']} position={[5.892, -0.754, -4.715]} scale={-0.313} />
      <mesh geometry={nodes.Sphere034.geometry} material={materials['Material.006']} position={[3.929, -0.754, 2.071]} scale={-0.313} />
      <mesh geometry={nodes.Sphere033.geometry} material={materials['Material.006']} position={[3.78, -0.721, 2.469]} scale={-0.313} />
      <mesh geometry={nodes.Sphere032.geometry} material={materials['Material.006']} position={[3.583, -0.741, 2.535]} scale={-0.313} />
      <mesh geometry={nodes.Sphere031.geometry} material={materials['Material.006']} position={[3.461, -0.724, 2.896]} scale={-0.313} />
      <mesh geometry={nodes.Sphere030.geometry} material={materials['Material.006']} position={[4.067, -0.556, 0.192]} scale={-0.313} />
      <mesh geometry={nodes.Sphere029.geometry} material={materials['Material.006']} position={[4.074, -0.488, -0.078]} scale={-0.313} />
      <mesh geometry={nodes.Sphere028.geometry} material={materials['Material.006']} position={[4.248, -0.572, -0.376]} scale={-0.313} />
      <mesh geometry={nodes.Sphere027.geometry} material={materials['Material.006']} position={[4.729, -0.556, -2.098]} scale={-0.313} />
      <mesh geometry={nodes.Sphere026.geometry} material={materials['Material.006']} position={[4.942, -0.522, -2.955]} scale={-0.313} />
      <mesh geometry={nodes.Sphere025.geometry} material={materials['Material.006']} position={[4.868, -0.556, -2.579]} scale={-0.313} />
      <mesh geometry={nodes.Sphere024.geometry} material={materials['Material.006']} position={[4.71, -0.488, -2.277]} scale={-0.313} />
      <mesh geometry={nodes.Sphere023.geometry} material={materials['Material.006']} position={[4.544, -0.522, -1.581]} scale={-0.313} />
      <mesh geometry={nodes.Sphere022.geometry} material={materials['Material.006']} position={[4.549, -0.438, -1.902]} scale={-0.313} />
      <mesh geometry={nodes.Cylinder062.geometry} material={materials['Material.014']} position={[8.912, -1.137, 3.296]} scale={0.834} />
      <mesh geometry={nodes.Cylinder061.geometry} material={materials['Material.014']} position={[9.358, -1.103, 1.632]} scale={0.834} />
      <mesh geometry={nodes.Cylinder060.geometry} material={materials['Material.008']} position={[9.218, -0.583, 0.34]} scale={0.727} />
      <mesh geometry={nodes.Cylinder059.geometry} material={materials['Material.014']} position={[9.585, -0.822, -3.005]} scale={0.834} />
      <mesh geometry={nodes.Cylinder058.geometry} material={materials['Material.014']} position={[8.972, -1.222, -0.667]} scale={0.834} />
      <mesh geometry={nodes.Cylinder057.geometry} material={materials['Material.007']} position={[9.024, -0.779, 1.495]} scale={0.528} />
      <mesh geometry={nodes.Cylinder056.geometry} material={materials['Material.007']} position={[8.912, -0.862, -1]} scale={0.528} />
      <mesh geometry={nodes.Cylinder055.geometry} material={materials['Material.007']} position={[9.17, -0.595, -1.87]} scale={0.528} />
      <mesh geometry={nodes.Cylinder054.geometry} material={materials['Material.014']} position={[8.156, -1.105, -3.893]} scale={0.834} />
      <mesh geometry={nodes.Cylinder053.geometry} material={materials['Material.007']} position={[9.354, -0.634, -4.43]} rotation={[Math.PI, -0.378, Math.PI]} scale={0.667} />
      <mesh geometry={nodes.Cylinder052.geometry} material={materials['Material.007']} position={[8.602, -0.886, -3.657]} rotation={[Math.PI, -0.378, Math.PI]} scale={0.667} />
      <mesh geometry={nodes.Cylinder051.geometry} material={materials['Material.014']} position={[8.571, -0.503, -5.669]} scale={0.834} />
      <mesh geometry={nodes.Cylinder050.geometry} material={materials['Material.014']} position={[7.552, -1.019, 4.819]} scale={0.834} />
      <mesh geometry={nodes.Cylinder049.geometry} material={materials['Material.008']} position={[7.994, -0.665, 4.072]} scale={0.727} />
      <mesh geometry={nodes.Cylinder048.geometry} material={materials['Material.008']} position={[6.65, -0.651, 3.921]} scale={0.727} />
      <mesh geometry={nodes.Cylinder047.geometry} material={materials['Material.014']} position={[4.186, -0.542, 4.929]} scale={0.834} />
      <mesh geometry={nodes.Cylinder046.geometry} material={materials['Material.014']} position={[5.663, -0.636, 4.977]} scale={0.834} />
      <mesh geometry={nodes.Cylinder045.geometry} material={materials['Material.009']} position={[5.495, -0.417, 3.856]} scale={0.443} />
      <mesh geometry={nodes.Cylinder044.geometry} material={materials['Material.007']} position={[6.498, -0.468, 4.78]} scale={0.667} />
      <mesh geometry={nodes.Cylinder043.geometry} material={materials['Material.007']} position={[4.835, -0.348, 4.779]} scale={0.667} />
      <mesh geometry={nodes.Cylinder042.geometry} material={materials['Material.014']} position={[-1.473, -0.171, 4.524]} scale={0.834} />
      <mesh geometry={nodes.Cylinder041.geometry} material={materials['Material.014']} position={[2.559, -0.749, 4.618]} scale={0.834} />
      <mesh geometry={nodes.Cylinder040.geometry} material={materials['Material.009']} position={[2.808, -0.507, 4.004]} scale={0.443} />
      <mesh geometry={nodes.Cylinder039.geometry} material={materials['Material.007']} position={[1.954, -0.468, 4.556]} scale={0.667} />
      <mesh geometry={nodes.Cylinder038.geometry} material={materials['Material.014']} position={[7.421, -1.097, -5.642]} scale={0.834} />
      <mesh geometry={nodes.Cylinder037.geometry} material={materials['Material.007']} position={[8.77, -0.394, -4.92]} rotation={[Math.PI, -0.378, Math.PI]} scale={0.667} />
      <mesh geometry={nodes.Cylinder036.geometry} material={materials['Material.014']} position={[5.553, -0.53, -6.482]} scale={0.834} />
      <mesh geometry={nodes.Cylinder035.geometry} material={materials['Material.007']} position={[6.218, -0.276, -6.336]} rotation={[Math.PI, -0.378, Math.PI]} scale={0.667} />
      <mesh geometry={nodes.Cylinder034.geometry} material={materials['Material.014']} position={[3.772, -0.38, -6.414]} scale={0.834} />
      <mesh geometry={nodes.Cylinder033.geometry} material={materials['Material.007']} position={[2.845, -0.185, -6.731]} rotation={[Math.PI, -0.378, Math.PI]} scale={0.667} />
      <mesh geometry={nodes.Sphere021.geometry} material={materials['Material.006']} position={[2.509, -0.415, -5.719]} scale={-0.202} />
      <mesh geometry={nodes.Sphere020.geometry} material={materials['Material.006']} position={[2.352, -0.479, -5.515]} scale={-0.202} />
      <mesh geometry={nodes.Sphere019.geometry} material={materials['Material.006']} position={[2.292, -0.322, -4.937]} scale={-0.202} />
      <mesh geometry={nodes.Sphere018.geometry} material={materials['Material.006']} position={[2.365, -0.146, -4.485]} scale={-0.202} />
      <mesh geometry={nodes.Sphere017.geometry} material={materials['Material.006']} position={[2.334, -0.363, -4.608]} scale={-0.202} />
      <mesh geometry={nodes.Sphere016.geometry} material={materials['Material.006']} position={[2.634, -0.068, -4.393]} scale={-0.202} />
      <mesh geometry={nodes.Sphere015.geometry} material={materials['Material.006']} position={[-0.096, -0.242, 2.337]} scale={-0.202} />
      <mesh geometry={nodes.Sphere014.geometry} material={materials['Material.006']} position={[0.237, -0.466, 2.5]} scale={-0.202} />
      <mesh geometry={nodes.Sphere013.geometry} material={materials['Material.006']} position={[2.219, -0.329, -0.236]} scale={-0.313} />
      <mesh geometry={nodes.Sphere012.geometry} material={materials['Material.006']} position={[1.426, -0.574, 1.185]} scale={-0.313} />
      <mesh geometry={nodes.Sphere011.geometry} material={materials['Material.006']} position={[1.615, -0.497, 0.823]} scale={-0.313} />
      <mesh geometry={nodes.Sphere010.geometry} material={materials['Material.006']} position={[1.796, -0.232, 0.027]} scale={-0.202} />
      <mesh geometry={nodes.Sphere009.geometry} material={materials['Material.006']} position={[1.491, -0.209, 0.431]} scale={-0.313} />
      <mesh geometry={nodes.Sphere008.geometry} material={materials['Material.006']} position={[0.828, -0.441, 1.655]} scale={-0.313} />
      <mesh geometry={nodes.Sphere007.geometry} material={materials['Material.006']} position={[0.533, -0.348, 1.945]} scale={-0.313} />
      <mesh geometry={nodes.Sphere006.geometry} material={materials['Material.006']} position={[0.012, -0.454, 2.802]} scale={-0.313} />
      <mesh geometry={nodes.Plane005.geometry} material={materials['Material.020']} position={[3.711, -0.511, -0.904]} scale={4.626} />
      <mesh geometry={nodes.Plane004.geometry} material={materials['Material.019']} position={[4.154, -0.504, -1.392]} scale={4.048} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['Material.018']} position={[4.098, -0.494, -1.691]} scale={3.337} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['Material.017']} position={[3.803, -0.422, -1.616]} scale={2.463} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.015']} position={[3.285, -0.311, -1.56]} scale={1.983} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.016']} position={[3.678, -0.514, -0.764]} scale={5.084} />
      <mesh geometry={nodes.Cylinder032.geometry} material={materials['Material.007']} position={[-0.742, -0.23, 4.561]} scale={0.667} />
      <mesh geometry={nodes.Cylinder031.geometry} material={materials['Material.014']} position={[0.45, -0.525, 4.802]} scale={0.834} />
      <mesh geometry={nodes.Cylinder030.geometry} material={materials['Material.008']} position={[3.482, -0.503, 4.231]} scale={0.727} />
      <mesh geometry={nodes.Cylinder029.geometry} material={materials['Material.009']} position={[7.298, -0.527, -5.618]} scale={0.443} />
      <mesh geometry={nodes.Cylinder028.geometry} material={materials['Material.009']} position={[8.442, -0.554, 3.391]} scale={0.443} />
      <mesh geometry={nodes.Cylinder027.geometry} material={materials['Material.008']} position={[7.476, -0.111, -6.034]} scale={0.426} />
      <mesh geometry={nodes.Cylinder026.geometry} material={materials['Material.007']} position={[8.922, -0.601, 2.499]} scale={0.528} />
      <mesh geometry={nodes.Cylinder025.geometry} material={materials['Material.007']} position={[-1.374, -0.037, 4.115]} scale={0.667} />
      <mesh geometry={nodes.Cylinder024.geometry} material={materials.Untitled} position={[-3.167, -0.084, 3.109]} />
      <mesh geometry={nodes.Sphere005.geometry} material={materials['Material.006']} position={[1.288, -0.069, -2.017]} scale={-0.572} />
      <mesh geometry={nodes.Sphere004.geometry} material={materials['Material.006']} position={[1.61, -0.253, -3.148]} scale={-0.572} />
      <mesh geometry={nodes.Sphere003.geometry} material={materials['Material.006']} position={[0.216, -0.125, -1.982]} scale={-0.572} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials['Material.006']} position={[0.227, 0.066, -2.133]} scale={-0.572} />
      <mesh geometry={nodes.Sphere001.geometry} material={materials['Material.006']} position={[1.207, 0.257, -3.16]} scale={-0.572} />
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.006']} position={[0.503, 0.193, -2.477]} scale={-0.572} />
      <mesh geometry={nodes.Cylinder022.geometry} material={materials['rock.001']} position={[-2.938, 2.61, -6.265]} rotation={[-Math.PI, 0.238, -Math.PI]} />
      <mesh geometry={nodes.Cylinder021.geometry} material={materials['Material.002']} position={[-3.464, 4.782, -3.608]} scale={[0.597, 0.585, 0.639]} />
      <mesh geometry={nodes.Cylinder020.geometry} material={materials['Material.002']} position={[-3.751, 2.136, -4.211]} scale={[0.597, 0.585, 0.639]} />
      <mesh geometry={nodes.Cylinder019.geometry} material={materials['Material.002']} position={[-4.632, 1.591, -1.645]} scale={0.942} />
      <mesh geometry={nodes.Cylinder018.geometry} material={materials['Material.002']} position={[-3.631, 2.097, -0.301]} scale={0.942} />
      <mesh geometry={nodes.Cylinder017.geometry} material={materials['rock.001']} position={[-5.18, 2.752, -1.05]} rotation={[0, -0.137, 0]} />
      <mesh geometry={nodes.Cylinder016.geometry} material={materials['rock.001']} position={[-4.216, 2.487, 0.382]} rotation={[0, -0.137, 0]} />
      <mesh geometry={nodes.Cylinder015.geometry} material={materials['rock.001']} position={[-2.602, 3.036, 1.099]} />
      <mesh geometry={nodes.Cylinder014.geometry} material={materials['Material.002']} position={[-2.809, 2.44, -3.411]} scale={[1, 1.439, 1]} />
      <mesh geometry={nodes.Cylinder013.geometry} material={materials['Material.005']} position={[-3.09, 0.997, -1.629]} />
      <mesh geometry={nodes.Cylinder012.geometry} material={materials['Material.004']} position={[-5.281, 0.174, -4.674]} scale={1.21} />
      <mesh geometry={nodes.Cylinder011.geometry} material={materials['Material.005']} position={[-4.611, 1.429, -3.065]} />
      <mesh geometry={nodes.Cylinder010.geometry} material={materials['rock.001']} position={[-3.073, 3.015, -4.523]} />
      <mesh geometry={nodes.Cylinder009.geometry} material={materials['Material.004']} position={[-1.552, 0.783, -3.159]} scale={1.21} />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials['Material.002']} position={[-2.486, 2.77, -5.599]} scale={1.259} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials['Material.004']} position={[-1.656, 0.823, -5.8]} scale={1.21} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials['Material.002']} position={[-2.668, 0.576, -1.145]} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials['rock.001']} position={[-0.752, 2.622, 1.652]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials.Untitled} position={[0.495, 0.757, 0.048]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.003']} position={[1.476, 0.608, -4.569]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.002']} position={[-0.37, 1.486, -5.142]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.002']} position={[-0.695, 0.874, -0.797]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.001']} position={[0, 1.471, -2.595]} scale={[0.542, 1.428, 0.697]} />
    </group>
  )
}

useGLTF.preload('../../public/tiny7.glb')
